name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    container: archlinux/base
    steps:
      - run: pacman -Syu --noconfirm base base-devel
      - uses: actions/checkout@v2
      - run: test/parseopt-consistency
